# Generated by Django 5.1.4 on 2024-12-18 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('pokemon_1', models.CharField(max_length=50)),
                ('pokemon_2', models.CharField(max_length=50)),
                ('pokemon_3', models.CharField(max_length=50)),
                ('pokemon_4', models.CharField(max_length=50)),
                ('pokemon_5', models.CharField(max_length=50)),
                ('pokemon_6', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedash.user')),
            ],
        ),
    ]
