# Generated by Django 5.1.4 on 2024-12-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedash', '0003_team_teampokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampokemon',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamPokemon',
        ),
    ]
